{% set name = "viasp" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - viasp-backend
    - viasp-dash
    - jupyter-server-proxy
    - clingraph
    - python-graphviz

test:
  imports:
    - viasp
    - viasp_server
  commands:
    - pip check
  requires:
    - pip

about:

  home: https://github.com/potassco/viasp
  summary: a visualization tool for clingo.
  license: MIT
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - stephanzwicknagl
