name: Deploy conda packages

on:
  workflow_dispatch:
    inputs:
      frontend:
        type: boolean
        required: true
        description: Publish frontend of main HEAD
      backend:
        type: boolean
        required: true
        description: Publish backend of main HEAD

jobs:
  backend:
    name: Publish backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        activate-environment: build

    - name: Install prerequisites
      run: |
        conda config --set anaconda_upload yes
        conda install conda-build anaconda-client
    - name: print info
      shell: pwsh
      run: |
        conda info
        conda list
    - name: publish conda package backend
      shell: pwsh
      run: |
        python .github/conda.py --package backend
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  frontend:
    name: Publish frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        activate-environment: build

    - name: Install prerequisites
      run: |
        conda config --set anaconda_upload yes
        conda install conda-build anaconda-client
    - name: print info
      shell: pwsh
      run: |
        conda info
        conda list
    - name: publish conda package frontend
      shell: pwsh
      run: |
        python .github/conda.py --package frontend
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

  wrapper:
    needs: [ frontend, backend ]
    name: Publish container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Building wrapper
        run: python -m build --sdist --wheel --outdir dist/;
      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          activate-environment: build

      - name: Install prerequisites
        run: |
          conda config --set anaconda_upload yes
          conda install conda-build anaconda-client
      - name: print info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: publish conda package wrapper
        shell: pwsh
        run: |
          python .github/conda.py --package viasp
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}